### PR TITLE
My last updates until the official release

### PR DESCRIPTION
**Pull request by osmelmc**

### CODE REVIEW

**Comment by eeveelo** [comment]
This is marked as a draft so I can't merge it yet. Did you still have more you were planning to add to it?

**Comment by osmelmc** [comment]
> This is marked as a draft so I can't merge it yet. Did you still have more you were planning to add to it?

Yes. I'm trying to fix one issue with the Mouth movements that is not soft enough al look like a fish some times.

**Comment by osmelmc** [comment]
> This is marked as a draft so I can't merge it yet. Did you still have more you were planning to add to it?

Yes. I'm trying to fix one issue with the Mouth movements that is not soft enough al look like a fish some times.

**Comment by osmelmc** [comment]
The update for the actor Stats need update the DLL too, so if is too much trouble, just ignore it.

**Comment by eeveelo** [comment]
> The update for the actor Stats need update the DLL too, so if is too much trouble, just ignore it.

What's it need, just the extra 3 stats added to the storage?

**Comment by osmelmc** [comment]
> > The update for the actor Stats need update the DLL too, so if is too much trouble, just ignore it.
> 
> What's it need, just the extra 3 stats added to the storage?

Yes because the Scripts to update the values are already on the sslActorAlias and are not working. Probably I did something wrong but my impression is that have to be added to the DLL too.
By the way where I can see the DLL codes, just for reference.

**Pull request merged**
