### PR TITLE
2021/11/02

### PR DESCRIPTION
**Pull request by osmelmc**

### CODE REVIEW

**Comment by osmelmc** [comment]
#28

**Review by eeveelo — COMMENTED** [review]
I'm still hesitant on the timer change. But I've gone ahead and added a native version of SexLabUtil.GetCurrentGameRealTime() to the SKSE plugin to replace the global one present here. This will cut down on a bit of potential script lag from having to do the calculation so frequently in papyrus. Probably overkill, but makes me feel a little better about it I guess.

Still waiting on SKSE to post their non-preliminary build though. Going to wait for that before pushing the updated SexLabUtil.dll. I already have a working AE update for PapyrusUtil and SexLabUtil both, but it requires a version of SKSE built from their github source since they haven't released the needed changes publicly yet.

**Comment by eeveelo** [comment]
Should also note that if the user has set their timescale to 0, than the timer breaks because gametime never changes. Should put some check at the start of animation that stops things from continuing if timescale is 0 and display some kind of error message. That or switch to the previous timer system whenever timescale is 0.

**Comment by osmelmc** [comment]
> Should also note that if the user has set their timescale to 0, than the timer breaks because gametime never changes. Should put some check at the start of animation that stops things from continuing if timescale is 0 and display some kind of error message. That or switch to the previous timer system whenever timescale is 0.

I did my research before make the function and is not necessary  set any check in this case, because if someone set the TimeScale on 0 all the game time will stop working and with him big part of the game. Of course I will set a min value of 1, just in case but probably pointless.
The users with experience recommend values between 6 and 60 to avoid issues and some mods like the [https://www.nexusmods.com/skyrimspecialedition/mods/18922](url) in theory can change the TimeScale value in middle of the sex scene but is mostly harmless since the negative effects of that are the same as the issue with the GetCurrentRealTime function and the Menu Mode.

**Comment by eeveelo** [comment]
> if someone set the TimeScale on 0 all the game time will stop working and with him big part of the game.

You should know by now how stupid a lot of general users are.

And setting a min value of 1 doesn't fix it beyond just fixing divide by zero problems. If time scale is 0, game time is unchanging regardless, so the return value of GetCurrentGameRealTime() never changes in turn, causing infinite loop. I've already tested this scenario and confirmed it.

**Pull request merged**
