### PR TITLE
2021/08/14

### PR DESCRIPTION
**Pull request by osmelmc**

### CODE REVIEW

**Comment by eeveelo** [comment]
I'm not sure including a default SexLabOfffsets.json is a good idea. Doing so would risk overwriting users existing custom ones generated from exports whenever they update.

**Comment by osmelmc** [comment]
> I'm not sure including a default SexLabOfffsets.json is a good idea. Doing so would risk overwriting users existing custom ones generated from exports whenever they update.

Is true but is worse don't include it since the SL Animation Loader can't process the Animation Offsets and are too many the Animations that need it (by the way my SLAL can process the Animation Offsets but apparently my skills aren't enough for make the Python to convert the TXT into JSON)
The best choice about the SexLabOfffsets.json is make it optional on the setup.

**Comment by eeveelo** [comment]
> > I'm not sure including a default SexLabOfffsets.json is a good idea. Doing so would risk overwriting users existing custom ones generated from exports whenever they update.
> 
> Is true but is worse don't include it since the SL Animation Loader can't process the Animation Offsets and are too many the Animations that need it (by the way my SLAL can process the Animation Offsets but apparently my skills aren't enough for make the Python to convert the TXT into JSON)
> The best choice about the SexLabOfffsets.json is make it optional on the setup.

Could rename it SexLabOffsetsDefault.json. Then in the script when importing it, import that file followed by the users own custom SexLabOffsets.json on top of it to overwrite with their changes.

**Comment by osmelmc** [comment]
> > > I'm not sure including a default SexLabOfffsets.json is a good idea. Doing so would risk overwriting users existing custom ones generated from exports whenever they update.
> > 
> > 
> > Is true but is worse don't include it since the SL Animation Loader can't process the Animation Offsets and are too many the Animations that need it (by the way my SLAL can process the Animation Offsets but apparently my skills aren't enough for make the Python to convert the TXT into JSON)
> > The best choice about the SexLabOfffsets.json is make it optional on the setup.
> 
> Could rename it SexLabOffsetsDefault.json. Then in the script when importing it, import that file followed by the users own custom SexLabOffsets.json on top of it to overwrite with their changes.

Is double work but looks like good idea.  I will see.

**Pull request merged**
